all:PhaME_run

##################################################################################################

##################################################################################################

PhaME_run:
	@echo "Copying complete Escherichia and Shigella genomes"
	mkdir -p $@
	mkdir -p PhaME_run/ref
	cp ../Eschericia2017/Escherichia_PhaME/ref/*.fna PhaME_run/ref
	cp ../Shigella2017/Shigella_PhaME/ref/*.fna PhaME_run/ref
	cp ../Eschericia2017/CompleteEscherichia/GCA_000026245.1_ASM2624v1/GCA_000026245.1_ASM2624v1_genomic.gff.gz PhaME_run/ref/


